packages:
  - '.'
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/vitest-plugin@1.2.7'
  - miniflare@5.20260923.0-alpha
  - wrangler@4.140.0
  - '@msw/cloudflare@0.1.0'
