ALTER TABLE email ADD COLUMN delivery_id TEXT;
ALTER TABLE email ADD COLUMN envelope_from TEXT;
ALTER TABLE email ADD COLUMN envelope_to TEXT;
ALTER TABLE email ADD COLUMN raw_r2_key TEXT;
ALTER TABLE email ADD COLUMN raw_size INTEGER;
ALTER TABLE email ADD COLUMN raw_sha256 TEXT;
ALTER TABLE email ADD COLUMN html_r2_key TEXT;
ALTER TABLE email ADD COLUMN text_r2_key TEXT;
ALTER TABLE email ADD COLUMN snippet TEXT;
ALTER TABLE email ADD COLUMN storage_version TEXT NOT NULL DEFAULT 'legacy';
ALTER TABLE email ADD COLUMN published_generation TEXT;
ALTER TABLE email ADD COLUMN received_at INTEGER;
ALTER TABLE email ADD COLUMN processed_at INTEGER;
ALTER TABLE email ADD COLUMN processing_status TEXT NOT NULL DEFAULT 'LEGACY';
ALTER TABLE email ADD COLUMN folder TEXT NOT NULL DEFAULT 'INBOX';
ALTER TABLE email ADD COLUMN trashed_at INTEGER;
ALTER TABLE email ADD COLUMN delete_state TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE email ADD COLUMN header_from TEXT;
ALTER TABLE email ADD COLUMN header_to TEXT;
CREATE UNIQUE INDEX email_delivery_id ON email(delivery_id) WHERE delivery_id IS NOT NULL;
CREATE UNIQUE INDEX email_raw_key ON email(raw_r2_key) WHERE raw_r2_key IS NOT NULL;
CREATE INDEX email_folder_listing ON email(user_id,folder,delete_state,email_id);
ALTER TABLE attachments ADD COLUMN generation TEXT;
ALTER TABLE attachments ADD COLUMN part_id TEXT;
ALTER TABLE attachments ADD COLUMN sha256 TEXT;
ALTER TABLE attachments ADD COLUMN storage_backend TEXT NOT NULL DEFAULT 'legacy';
ALTER TABLE attachments ADD COLUMN storage_version TEXT NOT NULL DEFAULT 'legacy';
ALTER TABLE attachments ADD COLUMN object_kind TEXT;
CREATE UNIQUE INDEX attachment_generation_part ON attachments(email_id,generation,part_id);
